import { ColorView } from './types';

export const Color: ColorView = () => null;
Color.black = () => null;
Color.blue = () => null;
Color.brown = () => null;
Color.clear = () => null;
Color.cyan = () => null;
Color.gray = () => null;
Color.green = () => null;
Color.indigo = () => null;
Color.mint = () => null;
Color.orange = () => null;
Color.pink = () => null;
Color.purple = () => null;
Color.red = () => null;
Color.teal = () => null;
Color.yellow = () => null;
Color.accentColor = () => null;
Color.primary = () => null;
Color.secondary = () => null;
Color.white = () => null;
